service: user-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  memorySize: 128

functions:
  signup:
    handler: routes.signup
    description: Submit user info  and starts login process.
    events:
      - http: 
          cors: true
          method: post
          path: user/signup 
  read:
    handler: routes.read
    description: Read your info.
    events:
      - http: 
          cors: true
          method: get
          path: user/read 
  login:
    handler: routes.login
    description: Login to your account.
    events:
      - http: 
          cors: true
          method: post
          path: user/login 
custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: false
    packager: 'npm'
  prune:
    automatic: true
    number: 3
  apiGatewayThrottling:
    maxRequestsPerSecond: 3000
    maxConcurrentRequests: 2000
  warningThreshold: 100
 
plugins:
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-api-gateway-throttling
  - serverless-cloudformation-resource-counter     
  - serverless-plugin-common-excludes
